#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloWorldMessenger.Resource", IsApplication=true)]

namespace HelloWorldMessenger
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int AppName1 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int AppName2 = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int LoginField = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int PassField = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int RegisterButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int SingInButton = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int button1 = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Dialogs = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int SingIn = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int AppName1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AppName2 = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int Login = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int LoginPassError = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int Password = 2130968581;
			
			// aapt resource value: 0x7f040007
			public const int Register = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int ServerAddress = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int SingIn = 2130968582;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
