#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloWorldMessenger.Resource", IsApplication=true)]

namespace HelloWorldMessenger
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int planets_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060006
			public const int AddDialogButton = 2131099654;
			
			// aapt resource value: 0x7f06001c
			public const int AppName1 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int AppName2 = 2131099677;
			
			// aapt resource value: 0x7f060011
			public const int AvatarView = 2131099665;
			
			// aapt resource value: 0x7f06001f
			public const int CreateDialogButton = 2131099679;
			
			// aapt resource value: 0x7f060010
			public const int DeleteDialogMenuButton = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int DialogListItem = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int DialogMembersListItem = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int DialogNameListItem = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int DialogTimeListItem = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int DialogsList = 2131099653;
			
			// aapt resource value: 0x7f060017
			public const int EditName = 2131099671;
			
			// aapt resource value: 0x7f060015
			public const int InfoField = 2131099669;
			
			// aapt resource value: 0x7f06000e
			public const int LogOutMenuButton = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int LoginField = 2131099666;
			
			// aapt resource value: 0x7f06000b
			public const int MessageField = 2131099659;
			
			// aapt resource value: 0x7f060007
			public const int MessageListItem = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int MessageTextListItem = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int MessageTimeListItem = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int MessagesList = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int NameField = 2131099668;
			
			// aapt resource value: 0x7f060018
			public const int OkButton = 2131099672;
			
			// aapt resource value: 0x7f060013
			public const int PassField = 2131099667;
			
			// aapt resource value: 0x7f060016
			public const int RegisterButton = 2131099670;
			
			// aapt resource value: 0x7f06000f
			public const int RenameDialogMenuButton = 2131099663;
			
			// aapt resource value: 0x7f06001a
			public const int SearchButton = 2131099674;
			
			// aapt resource value: 0x7f060019
			public const int SearchField = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int SearchUsersList = 2131099675;
			
			// aapt resource value: 0x7f06000c
			public const int SendMessageButton = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int ShowMessagesMenuButton = 2131099661;
			
			// aapt resource value: 0x7f06001e
			public const int SingInButton = 2131099678;
			
			// aapt resource value: 0x7f060020
			public const int UserListItem = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int UserLoginListItem = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int UserNameListItem = 2131099682;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DialogListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Dialogs = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DialogsMenu = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MessageListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Messages = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int MessagesMenu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Register = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RenameDialog = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SearchUsers = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SingIn = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int UserInfo = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int UserListItem = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int AppName1 = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int AppName2 = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000f
			public const int CreateDialog = 2130968591;
			
			// aapt resource value: 0x7f040018
			public const int DeleteDialog = 2130968600;
			
			// aapt resource value: 0x7f040009
			public const int Dialogs = 2130968585;
			
			// aapt resource value: 0x7f04001a
			public const int EnterName = 2130968602;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int Info = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int LogOut = 2130968598;
			
			// aapt resource value: 0x7f040004
			public const int Login = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int LoginPassError = 2130968584;
			
			// aapt resource value: 0x7f040013
			public const int Message = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int Messages = 2130968596;
			
			// aapt resource value: 0x7f04000a
			public const int Name = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int NoInternet = 2130968590;
			
			// aapt resource value: 0x7f040019
			public const int Ok = 2130968601;
			
			// aapt resource value: 0x7f040005
			public const int Password = 2130968581;
			
			// aapt resource value: 0x7f040011
			public const int Query = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int RegComplete = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int RegError = 2130968588;
			
			// aapt resource value: 0x7f040007
			public const int Register = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int RenameDialog = 2130968599;
			
			// aapt resource value: 0x7f040010
			public const int Search = 2130968592;
			
			// aapt resource value: 0x7f040012
			public const int SendMessage = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int ShowMenu = 2130968597;
			
			// aapt resource value: 0x7f040006
			public const int SingIn = 2130968582;
			
			// aapt resource value: 0x7f04001b
			public const int planet_prompt = 2130968603;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
